### ISSUE TITLE
Scene dim/brighten commands are switched

### ISSUE THREAD

**Issue by kuestess** [automategreen/home-controller#105]
Scene dim and brighten commands do the opposite of what they should - `sceneDim` brightens and `sceneBrighten` dims.  Looking through the code, appears that the command numbers are swapped - brighten should be 0x15 and dim should be 0x16.

**Comment by siburny** [comment]
Fixed in https://github.com/automategreen/home-controller/commit/0ffffc62edb6b0bf92e4ee82083bd7de4164751a

Also, v0.9.2 was published to NPM.

**Comment by kuestess** [comment]
Thanks @siburny!
