### ISSUE TITLE
[Question] Do the device events work when using a Hub instead of a PLM?

### ISSUE THREAD

**Issue by brendanjerwin** [automategreen/home-controller#21]
I'm using a PLM right now, but may want to switch to my hub in the future.

**Comment by brandongoode** [comment]
That depends on which Hub you have.  I've been using the old hub (2242-222).  The old hub has an IP PLM interface and works with the device events.  If you have one of the new Hub (2245-222), Insteon removed the PLM interface (i.e. breaking support for direct third party events).  

I'm creating an open source hardware solution to overcome this limitation.  I'm planning to post a new GitHub project in the next day or two with the details.

**Comment by brendanjerwin** [comment]
OK, but if it has the PLM interface it can do events. Good.

Looking forward to your hub!
