### ISSUE TITLE
FYI: A hub app to call home-controller

### ISSUE THREAD

**Issue by mark-hahn** [automategreen/home-controller#24]
Just thought I would give a shout-out for a new hub package I developed specifically to call home-controller functions.  I need this because I have a media center app I've written that needs to control lights and an HVAC app to control the thermostat.  I am also considering developing a third app with lets you manage scenes in a web-page.  I don't like monolithic apps that provide a lot of unrelated functions.

https://github.com/mark-hahn/insteon-hub

As the readme says it is not tested with lights yet, but since it just passes the URLs through as function calls I expect lights to work.

I will be adding websockets to receive events soon.  I need the HVAC app to act as a responder for commands from a wireless controller.

**Edit:** It should be able to drive ALL calls including low-level ones.

**Comment by brandongoode** [comment]
I like the concept.  Thanks for the IO class.
