### ISSUE TITLE
Linking returns null links.

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#25]
Both the PLM and the Dimmer Switch give their typical squak noises that I think means, things worked. However, no links are ever returned.  Can you see something I'm doing wrong?  Should I be reseting the PLM or the Dimmer first?

```javascript
var Insteon = require('home-controller').Insteon;
var hub = new Insteon();
var express = require('express');
var app = express();

var deviceMid = '[devicenum]';
var deviceBack = '[devicenum]';

var PLM_SERIAL = '/dev/tty.usbserial-[id]';

hub.serial(PLM_SERIAL, function () {
  hub.link(deviceBack, {}, function(links){
    console.log(links);

    hub.cancelLinking(function(){
      console.log('linking canceled');
    });

  });

});
```

**Comment by iDVB** [comment]
Nm...{shame} RTFM.. :+1: 

insteon.link() callback expects both **err** and **callback**

now it works just fine.

```javascript
  hub.link(deviceBack, null, function(err, links){
    console.log(links);

    hub.cancelLinking(function(){
      console.log('linking canceled');
    });

  });
```

**Comment by brandongoode** [comment]
Awesome. Glad you got it working.  If you have any more questions or find an issue, please feel free to open a new issue.
