### ISSUE TITLE
does home-controller support phonegap?

### ISSUE THREAD

**Issue by podema** [automategreen/home-controller#28]
Is it posible to use it with phonegap?
It would make it and interesting library, since you can share the same code for all the clients web, desktop (node-webkit) and mobile (via phonegap)

Could it be browserified?

**Comment by mark-hahn** [comment]
Shameless plug: Check out `insteon-hub`.  It will allow you to access
`home-controller` from any client.

**Comment by brandongoode** [comment]
It should be possible to make it work on PhoneGap or a similar solutions.  I've never tried, but would like to know when you get it working.  If you have to make any modifications, please issue a pull request.   I'm going to leave this issue open until you get it working.

**Comment by podema** [comment]
First of all Thanks Mark for the suggestion is it indeed an elegant solution, however i have to speak directly to insteon hub.

I will try browserify , hope will do the trick. You will be noticed! 
Thanks for your responses.
