### ISSUE TITLE
Is home-controller compatible with the 2012 hub?

### ISSUE THREAD

**Issue by podema** [automategreen/home-controller#29]
First of all pardon me if this is a dumb question.
however Insteon hub 2012 does not have a REST API , since i know from the dev notes for insteon hub 2012.
Nice library by the way!

**Comment by brandongoode** [comment]
It only works with the 2012 Hub (2242). The 2014 Hub (2245) removed the required TCP PLM connection and is not supported.

**Comment by podema** [comment]
Just what i want. 2014 has the REST API so it's easy to program to begin with.
Thanks for the aclaration
