### ISSUE TITLE
It seems like light.level(0) is ignored

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#31]
When I call `light.level(1-100)` it works great.
When I call `light.turnOff()` it also works great.
However, when I call light.level(0) when the level is currently > 1 ... it does nothing, no err and the light stays at its level.

**Comment by brandongoode** [comment]
Wow -- not sure how that's been missed for so long.  I see the issue `if(level)` would return false and it is checking the light's level.  I'll push a fix in a couple seconds.

**Comment by iDVB** [comment]
Great! Thanks @brandongoode

**Comment by iDVB** [comment]
Hmmm... maybe I'm doing something wrong... but it still seems to ignore light.level(0)
I've also made sure that I have version v0.6.0 installed. I've verified by looking at the package.json of home-controller that is sitting in my node_modules.

Cheers,
D

**Comment by brandongoode** [comment]
I haven't updated the version number on npm yet.  Use the following in your package.json to pull from GitHub directly:

```json
  "dependencies": {
    "home-controller": "git://github.com/automategreen/home-controller.git",
  }
```

**Comment by iDVB** [comment]
Worked! Thanks!

Just a thought... have you considered setting up a Gitter.im channel for this repo?
Many of the things I might have to ask (and likely others) are not necessarily "issues" as much as questions.
