### ISSUE TITLE
Can't get links() to work

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#33]
I was working with home-controller a fair bit a few weeks ago. Came back to it and now I feel like I'm back to square one. Can't seem to get the array of links off the PLM.

```javascript
var Insteon = require('home-controller').Insteon;

module.exports.bootstrap = function(cb) {

	var plm = new Insteon();
	var PLM_SERIAL_COM = '/dev/tty.usbserial-A901M7UC';

	plm.serial(PLM_SERIAL_COM);
	plm.links(null, function(err, links){
		console.log('LINKS:', links);
	});

};
```

What am I doing wrong? Also, I could not find one single example for using home-controller with `serial()`

**Comment by mark-hahn** [comment]
> Also, I could not find one single example for using home-controller with
serial()

My module `insteon-hub` uses serial. It might help to read it.

**Comment by iDVB** [comment]
Thanks, just looked. Sorry, but I'm not sure that helps any more. You don't seem to be connecting to an actual serial device... eg. `/dev/tty.usbserial-A901M7UD` 

Also, I can't seem to find where you are actually even using that serial connection at all.
I think your abstracting it for more dynamic use with routing. Just makes it that much more difficult for me atm.

I can't even seem to get a simple response back from the plm to test that its even working.
```javascript
	plm.serial(PLM_SERIAL_COM, function(){
		plm.info(function(err, info){
			console.log('info:', info);
		});
	});
```

**Comment by mark-hahn** [comment]
> /dev/tty.usbserial-A901M7UD

The serial device is passed in as an argument, `process.argv[2]`, and defaults to `/dev/insteon` which is what I named my serial port.

>  I can't seem to find where you are actually even using that serial connection at all.

The device is passed in to the `plm.serial` call like you do.  It is at the bottom.

> I can't even seem to get a simple response back
[here](http://stackoverflow.com/questions/5347962/how-to-connect-to-a-terminal-to-serial-usb-device-on-ubuntu-10-10).

**Comment by mark-hahn** [comment]
> I can't even seem to get a simple response back

I didn't look closely at your code, but have you verified that your serial port works?  You might check [here](http://stackoverflow.com/questions/5347962/how-to-connect-to-a-terminal-to-serial-usb-device-on-ubuntu-10-10).

**Comment by iDVB** [comment]
Well not sure what would flawlessly tell me its working. But I ran `ls /dev/tty.*` and got back `/dev/tty.usbserial-A901M7UD` which I have verified is the PLM as I ran it with and without it plugged in.

Also, if I run 
```
plm.serial(PLM_SERIAL_COM, function(){
		plm.info(function(err, info){
			console.log('info:', info);
		});
	});
```
with it unplugged I get a error and when I plug it in I get no error.... but I also get no console.log.

**Comment by brandongoode** [comment]
@iDVB 

You need to wait for the serial connection to finish before checking the links. Try se a connection listener:

```js
var Insteon = require('home-controller').Insteon;

module.exports.bootstrap = function(cb) {

    var plm = new Insteon();
    var PLM_SERIAL_COM = '/dev/tty.usbserial-A901M7UC';

    plm.serial(PLM_SERIAL_COM, function() {
      plm.links(null, function(err, links){
          console.log('LINKS:', links);
      });
    });

};
``

**Comment by brandongoode** [comment]
So you used a connection listener for your info example.  Is there an error object?

```js
    plm.serial(PLM_SERIAL_COM, function(){
        plm.info(function(err, info){
            console.log('err:', err);
        });
    });
```

**Comment by iDVB** [comment]
This also does not work...

```javascript
var Insteon = require('home-controller').Insteon;

var plm = new Insteon();
var PLM_SERIAL_COM = '/dev/tty.usbserial-A901M7UD';

plm.serial(PLM_SERIAL_COM, function(){
  plm.info(function(err, info){
    console.log('info:', info);
  });
});
```

When there are no links at all would this happen?

**Comment by iDVB** [comment]
When I run this.... 
```javascript
var Insteon = require('home-controller').Insteon;
	var plm = new Insteon();
	var PLM_SERIAL_COM = '/dev/tty.usbserial-A901M7UD';

	plm.serial(PLM_SERIAL_COM, function(){
		console.log('CONNECTED!');
    plm.links(null, function(err, links){
       console.log('links:', links);
    });
  });
```
I can see "CONNECTED!" in the console but NO links console out. But I would think if there were no links it would just console out empty. Also, I would think that plm.info() should give back something.

**Comment by brandongoode** [comment]
Yes, plm.info() should provide the info object if the PLM is working.  I'm suspistions there is some type of error.

You can also enable debuging by setting DEBUG=home-controller:insteon.
