### ISSUE TITLE
Not compatible with FRP? (Bacon.js)

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#34]
Now I could be way wrong on this...but I'm finding that the `links()` function does not seem to work like many other typical functions of other popular libs.  Eg. `fs.readFile()` when using FRP lib like [Bacon.js](https://baconjs.github.io/).

It's entirely possible that I'm doing something wrong, but something just doesn't seem right. Please bare with me since in order to explain, I need to mention things specific to Bacon.
Something like this works... (non-home-controller)
```javascript
var Bacon = require('baconjs').Bacon,
    fs = require('fs');
var read = Bacon.fromNodeCallback(fs.readFile, 'input.txt');
read.onError(function(error) { console.log("Reading failed: " + error); });
read.onValue(function(value) { console.log("Read contents: " + value); });
```

Also, this DOES work (home-controller)
```javascript
plm.serial(PLM_SERIAL_COM, function(){
	console.log('CONNECTED!');
	plm.links(null, function(error, link){
		console.log(link);
	})
});
```

However, this does NOT work (home-controller)
```javascript
plm.serial(PLM_SERIAL_COM, function(){
	console.log('CONNECTED!');
	var linksStream = Bacon.fromNodeCallback(plm.links, null);
	linksStream.onValue(function(link){
		console.log(link);
	});
});
```

The error is the *more* interesting thing to me...
```
TypeError: Cannot call method 'firstLink' of null
    at Insteon.links (/Users/me/Projects/leaf-box/node_modules/home-controller/lib/Insteon/index.js:1113:17)
```

When I go into [/lib/Insteon/index.html](https://github.com/automategreen/home-controller/blob/master/lib/Insteon/index.js#L1103) adding `console.log(this)` consoles out `null`. However, when I console the same in the typical, non-FRP version of home-controller it of course consoles out the plm/Insteon instance.

Any idea why this would happen?

**Comment by brandongoode** [comment]
The issue is the type of function `plm.links` is compared to `fs.readFile`.  The `fs.readFile` is a static function and doesn't act on the fs object.  `plm.links` is an instance function and needs the object (this) to work.

Use the following bacon.js call: https://github.com/baconjs/bacon.js/#bacon-fromnodecallback-object

```js
Bacon.fromNodeCallback(plm, links);
```

Also, you shouldn't need to pass the `null` argment.  It will default to null.

**Comment by iDVB** [comment]
Thanks so much @brandongoode !I new it had to do with context/scope and that readfile's functions where different (I reviewed the source) However, I didn't know the nomenclature of static vs instance functions.  I think I getting the issue now.  Let me give this other signature a try.
