### ISSUE TITLE
Unlinking / deleting links?

### ISSUE THREAD

**Issue by alistairg** [automategreen/home-controller#36]
I'm trying to work out how to remove links previously associated with the controller. The docs are a tad vague ;p

For example, some of the output from "links" is below:

`{
    "flags": "a2",
    "controller": false,
    "isInUse": true,
    "hasBeenUsed": true,
    "isLast": false,
    "group": 1,
    "id": "0651df",
    "data": [
      "00",
      "00",
      "ff"
    ],
    "onLevel": 0,
    "rampRate": 2000
  },
  {
    "flags": "e2",
    "controller": true,
    "isInUse": true,
    "hasBeenUsed": true,
    "isLast": false,
    "group": 254,
    "id": "0651df",
    "data": [
      "01",
      "07",
      "28"
    ],
    "onLevel": 1,
    "rampRate": 480000
  }`

....how would I go about calling `unlink()` to remove those two links?

**Comment by brandongoode** [comment]
It depends on the stated of the link you want to remove.  If the device is avalible you would use unlink and provide the device ID, group, and controller.

```js
insteon.unlink('0651df').then(...) //default group of 1 and defualts controller to false
insteon.unlink('0651df', {controller: true, group: 254}).then(...)
```

If, on the other hand, the device doesn't exist or you want to do it manually, you need to used the `removeLink` function.  It's documentation is a little more than vague.  It's undocumented. :-)

https://github.com/automategreen/home-controller/blob/affb243282ec241e4c44a7ef127a9b77a2f1639e/lib/Insteon/index.js#L1327

```js
insteon.removeLink('0651df', link).then(...) // remove link from device
insteon.removeLink(link).then(...) // remove link from hub
```

**Comment by siburny** [comment]
I added an option to delete a link to `insteon-link` program in 'bin' folder
