### ISSUE TITLE
Is there a way to simply monitor ALL events that cross the PLM?

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#38]
Looking for a simple way to listen for light events in general and not have to listen to EACH light for ALL of its events.

So the event would bubble the event type, the action and the device. This way you can listen for sweeping wide events.

?

**Comment by brandongoode** [comment]
The insteon object will emit a 'command' event for each command it recives that isn't a response.  The data for the event contains the device id and the raw Insteon command.

```js
insteon.on('command', function (data) {
  console.log('Device ID: ' + data.id);
  console.log('Command: ' + data.command1);
}
```

**Comment by iDVB** [comment]
When you say the "insteon object" do you mean...
`var Insteon = require('home-controller').Insteon;`
or
the plm... `var plm = new Insteon();`

I've tried both and when using `plm.on('command', function(command){console.log(command)});`
I don't see any events at all. I've tried turning on light switches on the wall and using my ISY to turn them on. 

However, I CAN use the plm to turn the light off and I CAN see that this light IS one of the links.

What am I missin?

**Comment by siburny** [comment]
It's actually both. First, you import the library through "require" command, and then you create an object of that class exactly like you have, but those statements are not mutually exclusive.

Example:
var Insteon = require('home-controller').Insteon;
var gw = new Insteon();

gw.on('connect', function () {
  console.log('Connection opened');
});

gw.on('close', function() {
  console.log('Connection closed');
});

gw.on('command', function (data) {
  console.log('Command: ', data);
}

gw.connect(host, port); // or gw.serial(port);

**Comment by jonn26** [comment]
The on 'command' event seems to only emit events from physical button presses on my insteon modules but not when sending hub triggered commands from this package (light.turnOn etc.).

 I am trying to make a simple UI representing the status of 4x lamp modules and would like it to show the current status (on, off, dim level) on them without having to poll the modules.

Is this possible?

**Comment by siburny** [comment]
I am not sure if it depends on how you linked your light and PLM, but I do receive 'command' event in both cases: in the first case (physical button) it's triggered by broadcast message and in the second case (turnOn function) is by 'ack' message from the devices

**Comment by siburny** [comment]
Just in case, my light switch is linked to PLM in both 'directions': as a responder and as a controller.

**Comment by jonn26** [comment]
I will double check they are linked both ways. What is interesting though and makes me think it is not a linking issue, is that when listening for events with the gw.on('command' I only get events from button presses, BUT when listening to commands via a light object, eg. lamp1.on('command' I see them from both button presses and when sending on commands. See my example below w/ output.

I guess listening for the events from each light will work for my use case but still curious why both ways are not showing all events like it sounds like they should.

```javascript
var Insteon = require('home-controller').Insteon;
var gw = new Insteon();
gw.connect('192.168.1.5', function(){
  console.log('Connected!');
});

gw.on('close', function() {
  console.log('Connection closed!');
});

gw.on('command', function(data) {
  console.log('GW Command: ' + JSON.stringify(data, null, 4));
});

var lamp1 = gw.light('AABBCC');

lamp1.on('command', function(group, data1, data2) {
       console.log('lamp1 Command: ' , group, data1, data2);
});

function lightOn (err) {
        if(err) {
                return gw.close();
        }
        console.log('Turn On Lamp1');
         lamp1.turnOn();
}

function lightOff (err) {
        if(err) {
                return gw.close();
        }
        console.log('Turn Off Lamp1');
         lamp1.turnOff();
}

setTimeout(lightOn, 1000);
setTimeout(lightOff, 3000);
```
Output: (note I have changed my device ids, also, I have two hubs which is why there are so many responses)

Connected!
Turn On Lamp1
lamp1 Command:  null 11 ff
Turn Off Lamp1
lamp1 Command:  null 13 00
##Pressed on button on lamp module
lamp1 Command:  1 11 00
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "999999",
        "extended": 0,
        "messageType": 6,
        "hopsLeft": 3,
        "maxHops": 3,
        "command1": "11",
        "command2": "00",
        "raw": "<redacted>"
    }
}
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "000005",
        "extended": 0,
        "messageType": 2,
        "hopsLeft": 1,
        "maxHops": 1,
        "command1": "11",
        "command2": "01",
        "raw": "<redacted>"
    }
}
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "000001",
        "extended": 0,
        "messageType": 6,
        "hopsLeft": 3,
        "maxHops": 3,
        "command1": "06",
        "command2": "00",
        "raw": "<redacted>"
    }
}
##Pressed off button on lamp module
lamp1 Command:  1 13 00
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "999999",
        "extended": 0,
        "messageType": 6,
        "hopsLeft": 3,
        "maxHops": 3,
        "command1": "13",
        "command2": "00",
        "raw": "<redacted>"
    }
}
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "000005",
        "extended": 0,
        "messageType": 2,
        "hopsLeft": 1,
        "maxHops": 1,
        "command1": "13",
        "command2": "01",
        "raw": "<redacted>"
    }
}
GW Command: {
    "standard": {
        "type": "50",
        "id": "AABBCC",
        "gatewayId": "000001",
        "extended": 0,
        "messageType": 6,
        "hopsLeft": 3,
        "maxHops": 3,
        "command1": "06",
        "command2": "00",
        "raw": "<redacted>"
    }
}

**Comment by siburny** [comment]
You are totally right: I was listening on Light object, not Insteon gateway.

**Comment by siburny** [comment]
ACK handler is different for each object so it's implemented in product objects, not gateway.

**Comment by brandongoode** [comment]
Looks like at the gateway level, for some reason, I didn't emit the on an ACK for commands sent.

https://github.com/automategreen/home-controller/blob/8b517685e08e97e367a1d16cc8941bd29087de42/lib/Insteon/index.js#L580-L584
```js
    if(!status || !status.command || !status.command.id ||
      (status.command.id.toUpperCase() !== id)) { // command isn't a response for a command we sent
      this.emit('command', cmd);
      break;
    }
```

If you want to get every event listen for the `'recvCommand'` event.
