### ISSUE TITLE
Scenes with ramp rates / levels

### ISSUE THREAD

**Issue by alistairg** [automategreen/home-controller#40]
I'm fighting the unintelligible Insteon command tables - is there a reason you didn't include support for "scene on at level" and "scene on at level with rate" type options?

It looks like it should be as simple as replacing the '00' in your sendAllLinkCmd function with the appropriate level (or half level / half rate) but that didn't seem to work.

Any thoughts / comments?

**Comment by siburny** [comment]
I don't think there is a way to do it. Technically, you specify what level/ramp dimmer needs to be at when you add it to a scene. Then you just trigger sceneOn and dimmer know what level and ramp to use.
