### ISSUE TITLE
cannot get dimming to work on wall switch

### ISSUE THREAD

**Issue by mark-hahn** [automategreen/home-controller#42]
I have be using home-controller for almost two years.  I've been controlling light bulbs and relays.  

I just tried controlling a new wall dimmer switch,  a 2477D, using the same code I've been using for light bulbs.  The switch works manually but I can't get dimming to work from home-controller.  Shouldn't a bulb and wall switch behave the same?

I've tried `light.turnOn(25,'fast')` and `light.level(25)`.  I know the `light` instance is good because it works with `turnOn()` and `turnOff()`.

The switch is brand new so it shouldn't have any link cruft in it.  I had to link from the PLM to the switch of course.

Any ideas?

**Comment by mark-hahn** [comment]
More info ...

Dim and brighten work, so I know the wall switch can receive a dim command.

I logged raw packets in and out of the PLM and I can see that my `turnOn()` is an `11FF` and `turnOn(50)` is `1180` (from memory) which means the `11` works for turning on but not level.

I'm suspecting that something changed in the firmware (a bug?) in the recent wall switches.  I'll continue to try different command codes.

**Comment by brandongoode** [comment]
Thanks for the heads up.  I haven't seen any issue yet. Do you know the firmware version of the switch?

**Comment by mark-hahn** [comment]
Can I find the version over the net?

**Comment by brandongoode** [comment]
The `info(id)` function should return the firmware version.

**Comment by siburny** [comment]
@mark-hahn is this still an issue? I have a dozen of 2477D in my house, and can control them (on/off/level) without any problems.

**Comment by mark-hahn** [comment]
If I remember correctly I had to buy the proper model and then it worked
fine.

**Comment by siburny** [comment]
I guess it might've been bad batch or maybe older firmware.

**Comment by siburny** [comment]
I ran into this issue with one of the dimmers yesterday. I could control it, but I didn't receive any events from it. From initial look, it was linked both ways (responder and controller). However, one of the links was `group 0` and one was `group 1`. I will delete all links tonight, and try to re-link the dimmer to see if it fixes the issue.

**Comment by siburny** [comment]
So my problem in the WAS linking. Even though PLM and light were cross linked, they both must have been with `group 1`. The tricky problem was to remove the links because unlinking did NOT work. I had to remove PLM records from database manually, and then factory reset the switch. After that, I cross-linked them again via SET buttons, and now I get all events correctly.
