### ISSUE TITLE
Can't seem to detect any events when manually turning on switches

### ISSUE THREAD

**Issue by iDVB** [automategreen/home-controller#43]
When I run this... this the "Light On!" gets consoled the one time since I'm programmatically turning on the light. However, if I then walk over to the switch and turn it off and on... nothing happens. I'm not getting the "Light On!" anymore... nor am I seeming to get any of the "command" events at all.

``` javascript
var plm = new Insteon();
var PLM_SERIAL_COM = '/dev/tty.usbserial-A6028O1E'; // /dev/tty.usbserial-A901M7UD


plm.serial(PLM_SERIAL_COM);

var frontrow = plm.light('2a330a');
frontrow.on('turnOn', function(){
    console.log("Light ON!");
});
frontrow.turnOn();

plm.on('command', function(command){
 console.log(command);
});
```

**Comment by brandongoode** [comment]
Make sure the PLM is a linked as a responder to the light.

**Comment by iDVB** [comment]
Oh. Does that mean that the PLM needs to be links as responder to all devices?
What does that look like in terms of `insteon.link()` call?

```
insteon.link('ABCDEF', 'gw', function(error, link) {
  // link data from gateway
});
```

??

**Comment by mark-hahn** [comment]
> What does that look like in terms of insteon.link() call?

I find it easiest to just push the buttons to link each controller.

**Comment by siburny** [comment]
@iDVB correct.
