### ISSUE TITLE
Toggle?

### ISSUE THREAD

**Issue by jlippold** [automategreen/home-controller#44]
Firstly, thanks for this awesome API.

Is there anyway to toggle a light, without first querying it's state?

Currently I have to check if device level === 0 to tell if its off, then I can turn it on. 

Is there a better way to simply toggle from off to on or on to off?

**Comment by brandongoode** [comment]
Glad you like it.

Unfortunately there is not the concept of toggle within the Insteon network.  You'll have to continue checking the state first.

**Comment by jlippold** [comment]
Ok, Wishful thinking I suppose. Thanks again,
