### ISSUE TITLE
light events not triggering on scene changes

### ISSUE THREAD

**Issue by jonn26** [automategreen/home-controller#47]
Events are emitted by the light object (such as 'turnOn' , 'dimmed', etc.) on physical button presses and commands sent via home-controller, but they don't appear to be emitted when manipulating lights by using scene commands such as insteon.sceneOn form home-controller.

Is this expected?

**Comment by brandongoode** [comment]
It should emit the same events for the scene commands.  Is it possible for you to run your code with the environment variable `DEBUG=home-controller*` and provide the output when you trigger the scene?

**Comment by siburny** [comment]
I can confirm this as well. Message that is sent from device (ack) is not recognized,

In my case on/off switch sends this:

> command1:"11"
> command2:"01"
> extended:false
> gatewayId:"239acf"
> hopsLeft:0
> id:"2d37ce"
> maxHops:1
> messageType:3
> raw:"02502d37ce239acf611101"
> type:"50"

Notice messageType is 3, which is direct ACK (not broadcast). Fix is easy, will submit a PR.

**Comment by siburny** [comment]
@brandongoode Your comment here https://github.com/automategreen/home-controller/blob/master/lib/Insteon/Light.js#L416 says "ack doesn't have group". Maybe they changed something, and group ack does have a group :)

**Comment by brandongoode** [comment]
@siburny Good catch and thanks in advance for the PR.  The comment is reference to standard direct message.

**Comment by brandongoode** [comment]
You could us the `handleAllLinkBroadcast` for type 3.  From the Insteon Dev Guide: 011 = ACK of ALL-Link Cleanup Message.  I think it would be the same logic as flipped type 2.

**Comment by siburny** [comment]
Sounds good

**Comment by siburny** [comment]
@jonn26 we just pushed a fix. Can you please test it on your setup?

**Comment by jonn26** [comment]
I can confirm I am now seeing light events on scene changes. @siburny & @brandongoode  thanks for the quick fix!
