### ISSUE TITLE
[dev] switch blanketjs to istambuljs

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#49]
Mocha has been updated to v3.x which breaks test coverage reporting: they removed html reporter. I suggest we switch to istambuljs (actively supported and maintained) that has built-in report formatters (including html). I already did the conversion locally in a branch, and it works great. I can create a PR if you agree.

**Comment by brandongoode** [comment]
That would be awesome. Thanks.

**Comment by siburny** [comment]
Also, SerialPort library was updated to v4.x, which requires a small change to home-controller.

Namely: 
1) new SerialPort (not new serialport.SerialPort).
2) autoOpen is part of the options objects

**Comment by siburny** [comment]
Fixed in #51
