### ISSUE TITLE
[dev] onLevel and rampRate functions

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#52]
If in "getter" mode, those two functions use `Light.info` and return relevant parameter (as int) in the callback.
If in "setter" mode, they return `promise` in the callback which is inconsistent.

It should be consistent and return the value. 
Relevant code fix: https://github.com/automategreen/home-controller/blob/unit-testing-improvements/lib/Insteon/Light.js#L345-L361

Another possible solution is to rewrite `.info` function to accept additional parameters (make it common) and then `onLevel` and `rampRate` become the aliases of it.

**Comment by siburny** [comment]
@brandongoode What do you think?

**Comment by siburny** [comment]
Here is the diff to be more visual: https://github.com/automategreen/home-controller/commit/04d8f710a5b8594768d67083a5101974fcb925f3#diff-fbd441aa479b0fe27a7e84409b81f61eL313

**Comment by brandongoode** [comment]
Good point.  I agree it is inconsistent.  I've just been ignoring the return value so have never noticed.

**Comment by siburny** [comment]
Fixed in https://github.com/automategreen/home-controller/commit/04d8f710a5b8594768d67083a5101974fcb925f3
