### ISSUE TITLE
[bug] incomplete messages

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#53]
Sometimes when two messages come in right after each other, second messages can be cut off and thus not processed (discarded).

Relevant line: https://github.com/automategreen/home-controller/blob/master/lib/Insteon/index.js#L820

In the `while` loop, there is a check for a start message signature, but there is not check for the length of the message. Example, `02629999990f117f060250999999ffffff2f117f` <- two incoming messages from a light. In some cases I experienced when Serial port returned a partial response `02629999990f117f060250` (and is still in the process of receiving the rest `999999ffffff2f117f`). While loop will iterate twice because there are two message start signatures: `0262` and `0250`. However, there will be no check performed if second message is complete or still buffering. Thus it will fail to parse it and return "null" for all fields, and then discard it.

It happens not often enough to cause problems, but often enough to notice it in the logs.

Fix is easy: change `while` to `if` thus making function return after first message, and then waiting for rerun of `checkStatus` function which does perform message length validation.

What do you think?

**Comment by brandongoode** [comment]
I'm not sure why I would have ever used a `while`.  Sounds like a good idea.  I normally use the TCP interface to the Hub so I've never seen this, but I can see it happening with the serial interface.

**Comment by siburny** [comment]
Sounds good.
