### ISSUE TITLE
[feature] Add garage door opener/status monitor

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#54]
I think it is essentially an iolink, but it would be nice to get open/close status rather than on/off.

I am in the process of acquiring one so should be able to test/add soon.

**Comment by brandongoode** [comment]
I don't have one, but I'm pretty sure it's a standard IOLink too.

**Comment by siburny** [comment]
I just got it: it is IOLinc with open/close sensor :)

I will add broadcast message parsing and also probably make event names "configurable". So for normal IOLinc it will emit "turnOn/turnOff", but in garage case "opened/closed". What do you think?

**Comment by brandongoode** [comment]
Sounds good.  I like having the event names configurable. That will keep from needing to create a new type and allows for it to simply be an alias.

**Comment by siburny** [comment]
Well, after playing with it for a couple of hours, I can say that this IOLinc is not a I/O module. It accepts 0x45, 0x46, 0x28 commands, but does NOTHING.

After searching github, I stumbled upon the correct commands to trigger the relay, and then read the status:
- To trigger the relay, you need to send 0x11 command with 0xFF level.
- To read the sensor status, you need to send 0x19 command with 0x01 (0x01 for sensor read, 0x00 for relay read) parameter, and ack with have the status.

Weird! So because of this it doesn't make sense to modify current IO.js - it's better to create a separate class.

**Comment by brandongoode** [comment]
That's strange -- but it is typical Insteon.

**Comment by siburny** [comment]
I am almost done, want to run naming by you:
- Emitted events should be called "open"/"close".
- Functions to open/close should have the same names.
- Status should be "opened"/"closed" (similar to door sensor)

Sounds good?

**Comment by brandongoode** [comment]
Yes sounds good

**Comment by siburny** [comment]
Just committed initial code. Still need to write some edge-case tests.

It works great on my garage door that I installed recently!

**Comment by siburny** [comment]
https://github.com/automategreen/home-controller/commit/b395a504e043c5d7fb277b66da767f5df5b17cfc

**Comment by siburny** [comment]
Fixed in https://github.com/automategreen/home-controller/commit/17b383a1995966c9d02028a52ac27eb011b1b7c6
