### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kcjonson** [automategreen/home-controller#55]
Is there a way to get information about device information without creating an object of the corresponding type?  I'm looking for basic reporting of events that happen on the device network.  I'm running the USB PLM, and I see that its pretty trivial to connect to it and listen for commands, but the payload is rather cryptic.  

The scenario that I'm dealing with is that I've received a generic "command" event from the PLM, and I want to translate it back into "The upstairs overhead light was turned on".  At this point I'm not actually storing the list of devices in a database in a way that I could create instances of their various classes and listen to specific events, is there a way to map the generic event back to a device specific  format?

**Comment by siburny** [comment]
It's impossible to guess the type of device based only on a received command (unless you have a database of device IDs and names). What you could do is query the device, and get device category and subcategory, which will tell you device's type (e.g. light, thermostat, etc.).

**Comment by kcjonson** [comment]
Hum, interesting.  Thanks for advice.  I suppose I should probably actually read that Insteon white paper pdf before I keep asking questions that are probably answered there.
