### ISSUE TITLE
[dev] mock data in unit tests

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#56]
All unit tests have mock data (sending/receiving), which all lower-cased. However, Insteon PLM sends all data in upper case. In some case (e.g. type, id, etc) library explicitly does `toUpperCase()`, but not in all cases (e.g. cmd1, cmd2, etc). I ran into this problem writing a test for Light class.

Proposal 1 (simple): call toUpperCase in socket's `data` handler.
Proposal 2 (slight more complicated): change all mock data in tests to be upper case.

@brandongoode what do you think?

**Comment by siburny** [comment]
After further investigation, it's actually socket (stream) that emits data in lower case. And I was wrong: both Serial and Network connection emit data lower case.

So the fix is simple: change `case` tests to lowercase as well.
https://github.com/automategreen/home-controller/blob/master/lib/Insteon/Light.js#L436
https://github.com/automategreen/home-controller/blob/master/lib/Insteon/Light.js#L441

**Comment by siburny** [comment]
Fixed in https://github.com/automategreen/home-controller/commit/123a194a4d5fd8cc1a39177c9352983060b31d35

**Comment by brandongoode** [comment]
Good catch thanks!
