### ISSUE TITLE
Dimming events not emitting from light

### ISSUE THREAD

**Issue by kcjonson** [automategreen/home-controller#57]
I'm getting `command`, `turnOn`, `turnOff` events from the light, but no `brightening`, `brightened`, `dimming`, or `dimmed` events.  No events trigger after physically dimming the light switch.

Powerline Modem is `2413u` and device firmware is `41 (i2CS engine)`

**Comment by kcjonson** [comment]
Set `DEBUG=home-controller:instead:light` when running app, no status messages for dim events coming from debug either.

**Comment by siburny** [comment]
Set DEBUG to * so we could see full Insteon traffic. It's possible dim command is not properly recognized.

**Comment by siburny** [comment]
I bet it has something to do with upper/lower case issue I discovered today: https://github.com/automategreen/home-controller/commit/123a194a4d5fd8cc1a39177c9352983060b31d35

**Comment by kcjonson** [comment]
DEBUG * didn't trigger anything for dim (but got a healthy stack for an off event)  I'll try applying the case sensitivity fix manually to see if it clears things up.

**Comment by siburny** [comment]
Never mind. Those commands were turnOn at tamp, not dim/brighten.

Let me record traffic with my switch and see if I can replicate the problem.

**Comment by kcjonson** [comment]
Im getting dead silence from the log after dimming the light to around 50% (manually on the hardware). Its not even hitting the `handleAck` event.  I'll double check that home-controller is actually getting a serial event to parse.

**Comment by kcjonson** [comment]
Yep, suspicion confirmed the `.on('data', function(data) {` function around line 129 in `index.js` isn't firing for dim events.

**Comment by siburny** [comment]
if `data` handle is not firing, then PLM doesn't send the data.

**Comment by kcjonson** [comment]
Indeed, not really sure what to do about that.  Debugging serial interface IO is getting a bit out of my area of experience.  That does confirm that its not directly an issue with the home-controller package though.

**Comment by siburny** [comment]
I just did a quick test with my dimmer:

1) press and hold "up" on the dimmer
First message: 0250112233000001cb1701 -> `brightening`
Second message (5s later): 0250112233000001c71800 -> `brightened`

2) press and hold "down" on the dimmer
First message: 0250112233000001cb1700 -> `dimming`
Second message: 0250112233000001cb1800 -> `dimmed`

I do get all messages :)

My dimmer's info:
`{ id: '112233',
  firmware: '45',
  deviceCategory: { id: 1, name: 'Dimmable Lighting Control' },
  deviceSubcategory: { id: 32 },
  isDimmable: true,
  isLighting: true,
  isThermostat: false }`

**Comment by kcjonson** [comment]
Thanks for checking, I'm going to dive into the `serialport` package and see if I can find a bug there. It doesn't seem to be picking up any communication either, which is really puzzling.

**Comment by siburny** [comment]
Also, just checking if you "cross-linked" gateway (PLM) and your dimmer. Otherwise, PLM doesn't get any command back.

**Comment by kcjonson** [comment]
Well, my lack of Insteon knowledge may be showing through, but I am seeing on/off events from the switches, if it were a linking issue, wouldn't all the events be failing to fire?

**Comment by siburny** [comment]
Very true. You wound't see those. It's also possible that your rampRate is too fast for it send any "in-progress" messages. or it could well be that there is a bug in the dimmer itself. A lot of "maybe's"

**Comment by brandongoode** [comment]
I would double check the link.  Some dimmers will send broadcast messages for on and off but not for  dim/brighten.  Make sure the PLM is linked as a responder to the switch.

**Comment by kcjonson** [comment]
Turns out, it was the links.  I used Indigo (desktop app) to re link everything (since I didn't end up trusting my own code) and the dim events started working again. Thanks for the tip, that was totally unexpected behavior! (TIL)

**Comment by brandongoode** [comment]
Ya -- Insteon has several "unexpected" behaviors.  Glad you got it working.
