### ISSUE TITLE
Unknown command in Light class

### ISSUE THREAD

**Issue by siburny** [automategreen/home-controller#64]
Recently, I noticed a lot of errors in my log file that look like this:
`No event for command - 00`

So apparently, when you request a light level (direct command '19'), it will respond with ACK containing the level. But since it's a known device, it will also try to "handleAck" it. "handleAck" will log the error because returned message will have Command1 = '00' (it's actualy Database Delta according to the docs). Basically, ACK will not reference original command ('19').

I propose a small "filter" that will check if arriving message is a response to the '19' command, and then ignore it (like this https://github.com/automategreen/home-controller/commit/df0b63a30cce6a10966eda66254222ad86c7704d)

@brandongoode what do you think?

**Comment by brandongoode** [comment]
@siburny -- Sorry for not responding. I completely overlooked this.  It looks good.  Thanks.
