### ISSUE TITLE
[Feature] node-red nodes

### ISSUE THREAD

**Issue by bfranske** [automategreen/home-controller#66]
It would be really nice to have node-red nodes which mapped the Insteon functionality of this project to node-red. I'm interested in swapping Misterhouse for node-red but the big thing keeping me on Misterhouse is the great Insteon support it has. If I can find some time I might work on this, but given my project list right now that could be a long while... As a starting point it would be worthwhile I think to see how this was done with the [ZWave nodes](https://github.com/OpenZWave/node-red-contrib-openzwave).

**Comment by siburny** [comment]
I did do similar thing: https://github.com/siburny/node-red-contrib-thethingsystem
I didn't use this library directly, but rather integrated it into the automation system called TheThingsSystem, which uses this library to talk to Insteon network.

But unfortunately, none of us have much of spare time to do this. Plus I don't think it should be part of this library itself.

**Comment by bfranske** [comment]
Just as an FYI for those looking to integrate Insteon with Node-RED you might want to take a look at the [insteon-mqtt project](https://github.com/TD22057/insteon-mqtt) which allows you to deal with Insteon devices as MQTT topics which you can obviously interact with in Node-RED and/or whatever other MQTT aware software you'd like. Not all Insteon commands and devices are supported yet but things are coming along quickly. It seems like this will soon meet my needs for bridging between Node-RED and Insteon.
