### ISSUE TITLE
Full Scene Example for lights?

### ISSUE THREAD

**Issue by funkju** [automategreen/home-controller#67]
I have been hacking code together and and a simple setup with 3 dimmable switches and using the Insteon USB controller to control.

I can control each of the lights separately just fine, but I cannot get scenes to work no matter what I do.

Could someone post some simple example code to see what I'm doing wrong?

This is what I'm currently using. 

```
var Insteon = require('home-controller').Insteon
var insteon = new Insteon()

const CONTROLLER = '3118b5'
const HOUSE_RIGHT = '3de6c1'
const HOUSE_LEFT = '40d6a4'
const SCONCES = '3dad15'

...

// connect via serial USB

...

// Does not work
  insteon.scene('gw', [
    SCONCES, HOUSE_RIGHT, HOUSE_LEFT
  ], {
    group: 2
  }).then(function () {
    insteon.sceneOn(2)
  })

// Works
var sconces = insteon.light(SCONCES)
sconces.turnOn()
```

**Comment by siburny** [comment]
When you create a scene, you need to specify the state of the responding devices. Read more here: https://github.com/automategreen/home-controller/#responder-object

Basically, when you turn ON the scene it doesn't mean "to turn ON all the devices" in that scene. Someone might have a scene that turns off some lights and turns on some other lights.

Try something like this to create a scene:
`insteon.scene('gw', [
    {id: SCONCES, 'level': 100},
    {id: HOUSE_RIGHT, 'level': 100},
    {id: HOUSE_LEFT, 'level': 100}
  ], {
    group: 2
  });
`

**Comment by funkju** [comment]
Sorry for the delay in the response. I made that change, but the scenes still don't work.

I do have an insteon 4 scene remote that does work. So I know it is possible....

Could you provide a super simple complete example? Of linking, creating a scene, and turning it on and off? Maybe I'm missing something silly, forgive me.

**Comment by siburny** [comment]
Here are two scripts that I just wrote to test this.

1) Script to add lights to a scene (in my case I chose Group 10):
```js
var Insteon = require('../').Insteon;
var host = 'COM10';

console.log('Connecting to ' + host);
var gw = new Insteon();

gw.on('connect', function () {
	gw.scene('gw',
		[ {id: 'ID1', 'level': 100}, {id: 'ID2', 'level': 100} ],
		{ group: 10 },
		function(err) {
			if(!!err) {
				console.log('Error: ', err);
				return;
			}

			console.log('scene done');
			gw.close();
		});  
});

gw.on('close', function() {
  console.log('Connection closed');
});

gw.serial(host);
```
This script produced the following output:
```
Connecting to COM10
scene done
Connection closed
```

2) Then I used this script to trigger sceneOn and verify lights' status:
```js
var Insteon = require('../').Insteon;
var host = 'COM10';

console.log('Connecting to ' + host);
var gw = new Insteon();

gw.on('connect', function () {
	var light1 = gw.light('ID1'),
		light2 = gw.light('ID2');
	
	light1.level(function(err, level) {
		if(!!err) {
			console.log('Error: ', err);
			return;
		}
		console.log('Light1 level: '+level);

		light2.level(function(err, level) {
			if(!!err) {
				console.log('Error: ', err);
				return;
			}
			console.log('Light2 level: '+level);

			gw.sceneOn(10, function() {
				console.log('sceneOn done');
				
				console.log('waiting 3 seconds');
				
				setTimeout(function() {
					light1.level(function(err, level) {
						if(!!err) {
							console.log('Error: ', err);
							return;
						}
						console.log('Light1 level: '+level);

						light2.level(function(err, level) {
							if(!!err) {
								console.log('Error: ', err);
								return;
							}
							console.log('Light2 level: '+level);
							gw.close();
						});
					});
				}, 3000);
			});
		});
	});
});

gw.on('close', function() {
  console.log('Connection closed');
});

gw.serial(host);
```

This scripts produced the following output.
```
Connecting to COM10
Light1 level: 0
Light2 level: 0
sceneOn done
waiting 3 seconds
Light1 level: 100
Light2 level: 100
Connection closed
```
As you can see my both lights were off, and after sceneOn they are both on.

**Comment by siburny** [comment]
Also, both of my lights are linked to Insteon PLM *BOTH* ways, so I can control them and get status notifications.

**Comment by siburny** [comment]
Are you all good now? Did it help?

**Comment by funkju** [comment]
I'm not sure. I haven't had a chance to play with it again. Feel free to close the issue for now.
