### ISSUE TITLE
Keypad support?

### ISSUE THREAD

**Issue by VanCoding** [automategreen/home-controller#68]
Hi guys!

Is it possible to utilize the Insteon KeyPads using this library?

I'd like to
- get an event when one of the buttons is being pressed or released
- turn the backlight of the keys on an off

Can this be done? If yes, are there any examples or docs that would help me on that?

Thanks! :)

**Comment by siburny** [comment]
It's definitely possible to set the state of each button: see here https://github.com/automategreen/home-controller/issues/35#issuecomment-123468305

As for events, I can't comment because I don't have one to test. I am sure that it sends something to PLM if you link it properly.

**Comment by VanCoding** [comment]
@siburny Thank you!
I saw that comment before and tried out the code, but it sadly didn't work.
I'm gonna try it again.

> I am sure that it sends something to PLM if you link it properly.

Do you maybe know, how to link it propertly?

And if I link it, how do I get the events?
With `insteon.on("command",function(){})`?

**Comment by siburny** [comment]
I usually link my devices manually through a Set buttons (hold `controller` for a few sec until it's blinking, then `responder`). You should link both ways: one PLM is controller, one keypad is controller.

To monitor all incoming messages, listed for `recvCommand` event

**Comment by VanCoding** [comment]
@siburny I've got the events working, thanks.

Sadly, I'm still unable to set the led state of the buttons.
I've found this document: http://cache.insteon.com/developer/2334-xxx2486xdev-042013-en.pdf
Which made clear, why the code in #35 should work. But sadly, the keypad does not react to this command. Sometimes, i get a success response, but still nothing happens.

What's strange is that I can't get anything from the keypad. Neither links(), info(), or ping() does work.
Even though I've linked it all together.

**Comment by siburny** [comment]
Both `Info` and `Ping` should work even without linking the devices. So there is definitely something wrong with either communications or device itself. Is it possible PLM and the keypad are too far? Have you tried resetting your Keypad to factory defaults just in case?

**Comment by siburny** [comment]
Were you able to resolve the issue?

**Comment by VanCoding** [comment]
@siburny I tried again 2 weeks ago and got all needed commands working, without changing the setup. Also info and ping.

But it seemed not to be very reliable. The commands failed half of the time and hat pretty long response times, eventhough they were located next to each other and wired to the same power source. But I'm don't think that it's a problem of this library, so I think this issue can be closed ;)

A bit more information for potential future readers:
- I bought the 6 button, non-dimmable keypad. But when I found out that it's basically just a 5 button keypad, because the on & off button are linked together I was a bit disappointed and watched out for a new keypad of another manufacturer.
- Because it's just a 5-button keypad, you can't control the backlight of the on/off buttons individually. If the ON-button's light is off, then the OFF-buttons light is always on, and vice versa. So it is impossible to have turn off all LEDs at the same time (except if you disable the keypad's backlight completely)
- In order to get all the button events, you need to link each button by itself to the controller. You can't link the entire keypad at once (or I couldn't find out how)
- The button-press events are delayed around 2 seconds. So the keypad might not be suitable for situations, where you need immediate feedback when pressing, holding and then releasing the button. "Click" events are fast though.
- For some commands, you need to disable the programming lock first. Search the docs for "programming lock" to find the command to enable disable the lock.

**Comment by siburny** [comment]
Thanks for detailed feedback!

**Comment by majortom64** [comment]
@VanCoding Just to be clear, the 6 button and 8 button KeyPadLincs are exactly the same, but can operate in either mode. If you wanted a 6 - button, set it into 8 button mode and use the large 2 button key tops. There are then two choices: just link both buttons under the key top to the same thing, or only use one of the two and expect that both will be pushed at the same time.

**Comment by siburny** [comment]
Do the following:
1) Tap the KeypadLinc scene button of choice
2) Press and hold KeypadLinc’s Set button until it beeps (about 3 seconds). KeypadLinc scene button LED will blink.
3) Press and hold the PLM's Set button until it beeps or its LED flashes

You have to repeat these steps for all buttons on your keypad.

More info here if you need it: https://cache-m2.smarthome.com/manuals/2487sqs.pdf
