### ISSUE TITLE
For lights - 'turnon' and 'turnoff' emitted from ACK of extended commands

### ISSUE THREAD

**Issue by brandongoode** [automategreen/home-controller#69]
'turnon' is emitted with the ack from `insteon.linkAt`
'turnoff' is emitted with the ack from `light.info`

Need to add logic to ignore the ack if the status is an extended command.

**Comment by siburny** [comment]
What if ignore all acks if there is `status` set. That way we know it's a response to our command vs other action.

**Comment by brandongoode** [comment]
@siburny - I agree.  Although I think we would make it configurable.  In the past I've used code that used the emits, but it lead to some confusing behavior.

**Comment by siburny** [comment]
@brandongoode we should also update package.json with the new version number (0.8.0)
