### ISSUE TITLE
v0.8 Release

### ISSUE THREAD

**Issue by brandongoode** [automategreen/home-controller#71]
@siburny -- Do you have anything else you want to add before I publish 0.8 to npm?

**Comment by siburny** [comment]
Please go ahead. My changes are mostly just style changes (unification) and more unit tests (We are at 91%!).

**Comment by siburny** [comment]
@brandongoode Should we remove `spark` from optional dependencies? It's not used anywhere in the code, and it's not longer `spark` anyway.

**Comment by brandongoode** [comment]
ya -- good idea.  Probably would be a good idea to update the other decencies too.

**Comment by brandongoode** [comment]
Just published to npm.

**Comment by siburny** [comment]
SerialPort requires small code changes. I will do it now.

**Comment by brandongoode** [comment]
@siburny Thanks
