### ISSUE TITLE
[Feature] Integration with Node-Red

### ISSUE THREAD

**Issue by rperciaccante** [automategreen/home-controller#74]
Integration with Node-Red, or examples of how to integrate with the NodeRed settings.js file would be VERY much appreciated, as this would allow me to replace an entire home automation system with this platform.

**Comment by siburny** [comment]
Unfortunately, there is no way to directly integrate it into Node-RED. You would have to write custom nodes to inject events and perform actions.

**Comment by siburny** [comment]
See more here: https://github.com/automategreen/home-controller/issues/66

**Comment by bfranske** [comment]
Just as an FYI for those looking to integrate Insteon with Node-RED you might want to take a look at the [insteon-mqtt project](https://github.com/TD22057/insteon-mqtt) which allows you to deal with Insteon devices as MQTT topics which you can obviously interact with in Node-RED and/or whatever other MQTT aware software you'd like. Not all Insteon commands and devices are supported yet but things are coming along quickly.
