### ISSUE TITLE
powerlinc-modem connect uand usage

### ISSUE THREAD

**Issue by zirexix** [automategreen/home-controller#76]
Hi,
How do I use to connect to 
http://www.insteon.com/2412s-powerlinc-modem-serial.html
over USB serial and

**Comment by siburny** [comment]
You can use `serial(COMPORT)` function to do that.
You can see a sample programs in the `bin` folder (namely https://github.com/automategreen/home-controller/blob/master/bin/insteon-light).

**Comment by comarius** [comment]
Appreciate. Thank you.
