### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by comarius** [automategreen/home-controller#77]
I am looking for Insteon modem development serial for PLM specific to thermostat. Does it happen to know a good documentation about the commands, extedended, see you used them extensively in the thermostat code.
Thank you.

**Comment by siburny** [comment]
First link in the [search results](https://www.google.com/search?q=insteon+developer+notes+thermostat) is what I used.

**Comment by zirexix** [comment]
Thank you. How I could missed that. That's what I need.
Please close
