### ISSUE TITLE
HubPro PLM Connection

### ISSUE THREAD

**Issue by rasod** [automategreen/home-controller#78]
Hello, I'm trying to get home-controller running on a HubPro (HomeKit Hub). Anyone you has them knows your are lucky if they last more then a year and Insteon hasn't update the firmware in over 2 years. Inside the Hub is basically a Beagle Board with a PLM hooked up on UART4.

Home-controller seems to connect to the modem but I can't seem to get it to respond to any commands.

Am I missing something?

```javascript
var Insteon = require('home-controller').Insteon
var hub = new Insteon();

hub.serial('/dev/ttyS4', function(){
  console.log('Connected!');
  init();
});

function init(){
  console.log("Init");

  hub.info(function(err, info) {
    console.log("Hub Info: " + info);
  })

  hub.links(function(err, links) {
    console.log("Links: " +  links)
  })
}

```
```javascript
DEBUG=home-controller:insteon node test.js
  home-controller:insteon connecting /dev/ttyS4 +0ms
  home-controller:insteon connected +186ms
Connected!
Init
  home-controller:insteon Send: {"command":{"raw":"0260","type":"60"},"deferred":{"promise":{}},"timeout":5000} +95ms
  home-controller:insteon insteon.links - id: null +38ms
  home-controller:insteon Already running a command - queuing command: {"raw":"0269","type":"69"} +5ms
  home-controller:insteon sendCommandTimout - status: {"command":{"raw":"0260","type":"60"},"deferred":{"promise":{}},"timeout":5000} +5s
  home-controller:insteon Resend: {"command":{"raw":"0260","type":"60"},"deferred":{"promise":{}},"timeout":5000} +3ms
  home-controller:insteon sendCommandTimout - status: {"command":{"raw":"0260","type":"60"},"deferred":{"promise":{}},"timeout":5000} +5s
  home-controller:insteon Send: {"command":{"raw":"0269","type":"69"},"deferred":{"promise":{}},"timeout":5000} +14ms
Hub Info: undefined
  home-controller:insteon sendCommandTimout - status: {"command":{"raw":"0269","type":"69"},"deferred":{"promise":{}},"timeout":5000} +5s
  home-controller:insteon Resend: {"command":{"raw":"0269","type":"69"},"deferred":{"promise":{}},"timeout":5000} +3ms
  home-controller:insteon sendCommandTimout - status: {"command":{"raw":"0269","type":"69"},"deferred":{"promise":{}},"timeout":5000} +5s
Links: 
```

**Comment by siburny** [comment]
What about `err`? is it defined?

I personally don't have any experience with BB. [This page](http://beaglebone.cameon.net/home/serial-ports-uart) suggests to use `/dev/ttyO4`: does it exist on your board?

**Comment by rasod** [comment]
err is there to catch any errors produced by the hub commands, both return null.

I found that same page, tty04 links to S4 that's why used it. Since I got the "Connected!" response I assumed that the port was already enabled. Found [another (newer) page ](https://stackoverflow.com/questions/35881761/enabling-uart-on-beaglebone-black?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) on how to enable the port. Will try that too.

**Comment by siburny** [comment]
So it looks like it's an issue with configuring BB rather than with this library.
I will close the issue, but please do leave a comment if you solve this problem.

**Comment by siburny** [comment]
If we parse that output and just keep the lines that indicate incoming data:
```
  home-controller:insteon Rcvd: ff +100ms
  home-controller:insteon Rcvd: ff +20ms
  home-controller:insteon Rcvd: ff +36ms
  home-controller:insteon Rcvd: ff +26ms
  home-controller:insteon Rcvd: d9fc +22s
  home-controller:insteon Rcvd: d9f9 +265ms
  home-controller:insteon Rcvd: 0849123857 +19s
  home-controller:insteon Rcvd: 08 +206ms
  home-controller:insteon Rcvd: f77d088c +4ms
  home-controller:insteon Rcvd: 08 +4s
  home-controller:insteon Rcvd: 49323b47ff +3ms
  home-controller:insteon Rcvd: 280449 +378ms
  home-controller:insteon Rcvd: 1dfbfd +3ms
```
which translates into this output:
```
ffffffffd9fcd9f9084912385708f77d088c0849323b47ff2804491dfbfd
```
This output doesn't contain any valid messages (message starts with `02`).
I suspect maybe you used a wrong baudRate. Try changing to something like that:
```
hub.serial('/dev/ttyS4', {baudRate: 57600}, function(){
  console.log('Connected!');
  init();
});
```

**Comment by siburny** [comment]
That IS confusing; need to check it. But I am glad you figured it out.
