### ISSUE TITLE
Lighting Event Emitter question

### ISSUE THREAD

**Issue by jlippold** [automategreen/home-controller#79]
I'm trying to use the lighting events as described here 
https://github.com/automategreen/home-controller#lighting-events

I notice that the `light.on('turnOn'...` event is emitted with toggling a light via this api, but if I turn on the device via a wall switch the event is not emitted.

Am I doing something wrong, or is this a known limitation? FWIW, I have a bunch of motion detectors which emit events to this API just fine. Thanks for the help

**Comment by siburny** [comment]
Make sure you linked PLM and Light both ways.

**Comment by jlippold** [comment]
Hey @siburny, I'm not sure I understand what that means or how to do that. I think I have the 2242 hub (the 2013 pre alexa/homekit model) if that matters.

**Comment by siburny** [comment]
Ah, sorry for not being descriptive. All links in Insteon are "directional": every link has "controller" and "responder". So what you need to do is to create 2 links: Hub (controller) -> Light (responder) and Light (controller) -> Hub (responder). You are most likely missing the last one.

**Comment by jlippold** [comment]
Ahh ok wasn't aware of that. For each new insteon device, I load the insteon app on my iphone, click add device, i tell it the device type, and it tells me to hold some button on the device, then the link is successful. I suppose this is hub -> light as in your description. How do I do light -> hub? I've never done it.

**Comment by siburny** [comment]
I am not sure how to do that through the app/hub, but I usually do using "set" buttons.
1) Put your light into the linking mode by holding the "set" button (little button under the paddle).
2) Then press and hold set button on the hub.

You can read more info about linking [here](https://forum.insteon.com/forum/main-category/insteon-products/insteon-hub-app/ios-aa/88909-linking-insteon-devices-with-hub-pro?p=88927#post88927).
Relevant part for doing linking both ways:
> For instance if I want to setup a light switch. First I click and hold the small button on the back of the hub. After a couple seconds it makes a noise and flashes green. Then I hold down the set button on the switch for a couple seconds it makes a noise and then another noise confirming its linked. Next you do it in the reverse. Hold down the switch set button until it makes a noise and flashes green. Then you hold down the set button on the hub until it beeps confirming it's linked. Then if you go in the Insteon app or Home app you will see the device listed under "Default Room" where you can adjust all the settings for it.

**Comment by jlippold** [comment]
Damn dude, I've had insteon for like 5 years and had no idea. Thanks, I'll try it

**Comment by jlippold** [comment]
Thanks @siburny that worked, but it works intermittently. Sometimes, I flip on the switch and the event isn't emitted. Is there anyway to increase the reliability, or is this just an issue with insteon devices in general.

**Comment by siburny** [comment]
It is most likely related to some communication issues. On my setup I get 99% of events.

**Comment by jlippold** [comment]
ok thanks for the help
