### ISSUE TITLE
'Insufficient data to continue' with 2242 Hub

### ISSUE THREAD

**Issue by kuestess** [automategreen/home-controller#83]
@siburny Using consecutive commands with a 2242 hub degrades hub performance to the point that it eventually becomes very slow or even unresponsive to commands.  Running in debug mode shows that `checkStatus` consistently returns 'parsing - insufficient data to continue' with a buffer equal to '15'.  After that, it retries the `checkStatus` and eventually is successful, but at the expense of very slow response.  Adding a 500ms delay to `checkStatus` nearly eliminates the delays from insufficient data.  Changing the `connect` function as below seemed to work:

`socket.on('data', function (data) { 
debug('Rcvd:', data); 
that.buffer = that.buffer + data; 
setTimeout(function(){
that.checkStatus()},500)
});`

Several users have had this issue with my homebridge plugin which requires a persistent connection.  Probably not use this library was intended for, but the above change seems to make it work fairly well with 2242 hubs.  Happy to submit a PR if you're open to it!

**Comment by siburny** [comment]
Hey @kuestess. `checkStatus` is called everytime there is data received via `data` event handler. It probably depends where you connect to, but when I can connect to serial port I rarely see "insufficient data". By the time 'data' handler is called buffer would have a full message in it.

Is it possible for you to send a full debug output?

**Comment by siburny** [comment]
When you add slight delay via `setTimeout` you are not reducing a number of calls to `checkStatus`; you are just delaying them by a specific amount. So if the first delay call would get a full message, others would see an empty buffer anyway and exit with "insufficient data" message.

**Comment by kuestess** [comment]
@siburny Below is a debug log from my 2245 running a script to get links for a device.  You can see repeated buffer of '15' followed by 'insufficient data to continue'.  This is similar to what I saw with the 2242, although less frequent.  Perhaps throttling the checkStatus isn't the answer, but It seems like we're throwing more requests than the hub can handle in a short amount of time.  Net result is that all requests take longer, or are less reliable given the repeated retires.  Perhaps a user-configurable throttle to tune the rate of requests to the hub?

` home-controller:http command sent +77ms
  home-controller:http making request /buffstatus.xml +54ms
  home-controller:http good buffer 151515151515151515 +3ms
  home-controller:insteon checkStatus - buffer: 151515151515151515 +144ms
  home-controller:insteon checkStatus - status: {"command":{"cmd1":"2F","cmd2":"00","extended":true,"userData":["00","00","0FF7","01"],"type":"62","checksum":202,"raw":"02624A949C1F2F0000000FF7010000000000000000CA","id":"4A949C"},"deferred":{"promise":{}},"timeout":5000} +0ms
  home-controller:insteon parsing - message skipped +0ms
  home-controller:insteon checkStatus - buffer: 15151515151515 +2ms
  home-controller:insteon checkStatus - status: {"command":{"cmd1":"2F","cmd2":"00","extended":true,"userData":["00","00","0FF7","01"],"type":"62","checksum":202,"raw":"02624A949C1F2F0000000FF7010000000000000000CA","id":"4A949C"},"deferred":{"promise":{}},"timeout":5000} +0ms
  home-controller:insteon parsing - message skipped +0ms
  home-controller:insteon checkStatus - buffer: 1515151515 +1ms
  home-controller:insteon checkStatus - status: {"command":{"cmd1":"2F","cmd2":"00","extended":true,"userData":["00","00","0FF7","01"],"type":"62","checksum":202,"raw":"02624A949C1F2F0000000FF7010000000000000000CA","id":"4A949C"},"deferred":{"promise":{}},"timeout":5000} +0ms
  home-controller:insteon parsing - message skipped +0ms
  home-controller:insteon checkStatus - buffer: 151515 +1ms
  home-controller:insteon checkStatus - status: {"command":{"cmd1":"2F","cmd2":"00","extended":true,"userData":["00","00","0FF7","01"],"type":"62","checksum":202,"raw":"02624A949C1F2F0000000FF7010000000000000000CA","id":"4A949C"},"deferred":{"promise":{}},"timeout":5000} +0ms
  home-controller:insteon parsing - message skipped +0ms
  home-controller:insteon checkStatus - buffer: 15 +2ms
  home-controller:insteon checkStatus - status: {"command":{"cmd1":"2F","cmd2":"00","extended":true,"userData":["00","00","0FF7","01"],"type":"62","checksum":202,"raw":"02624A949C1F2F0000000FF7010000000000000000CA","id":"4A949C"},"deferred":{"promise":{}},"timeout":5000} +0ms
  home-controller:insteon parsing - insufficient data to continue - 2 +0ms`

**Comment by siburny** [comment]
Interesting thing about those '15' messages. Apprently, '151515' response means Hub is busy: more info https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/insteon-mnsandler/109361-periodically-get-unable-to-communicate-with-insteon-powerline-interface?p=1125637#post1125637

**Comment by siburny** [comment]
Please test with the latest version and let me know if this issue persists.
