### ISSUE TITLE
Publish 0.9 To NPM

### ISSUE THREAD

**Issue by rasod** [automategreen/home-controller#93]
Will 0.9 be released to NPM? Older versions use older versions of serial port dependency which is not compatible with newer node.js versions.

**Comment by siburny** [comment]
Unfortunately, I don't access to NPM repository.

@brandongoode can you please look into this?

**Comment by siburny** [comment]
If you want to use the latest version from GitHub you can just add this to your package.json:
```
  "dependencies": {
    "home-controller": "automategreen/home-controller"
  } 
```

**Comment by brandongoode** [comment]
Sorry -- I should have done this a while ago.  0.9 has been pushed to npm.
